### ISSUE TITLE
[Questions] Some questions

### ISSUE THREAD

**Issue by Zenrac** [AndyTempel/weebapi#2]
Hi, I tested your API Wrapper and he's pretty simple and easy to use.
But I feel like there are no many informations/doc, so I have some questions to ask you

1. Did this API Wrapper is using the V1 or the V2 of the API ?
- The answer is V2, I found it in the code.

2. Are you planning to add the whitelisted-only functionalities ? (**generate_image**, **generate_status, generate_waifu_insult** and **generate_license**)

3. Are you going to detail the available functionalities except get_random ?

4. That's not really a question but what about adding the list of the available image_type. (https://hastebin.com/ayekigojed.diff)

**Comment by AndyTempel** [comment]
1. Yes it's V2
2. Whitelisted func are in the making and will be released today or maybe tomorrow
3. Documentation will be released with image generation.
4. You can get all available types with `get_types`

**Comment by Zenrac** [comment]
Ty for answers ;)
